### ISSUE TITLE
1128-ToDo

### ISSUE THREAD

**Issue by ysong4** [ysong4/sda-notification#1]
TODO:

- [x] 1. Update the API for creating new notification
- [x] 2. Implement Observer
- [x] 3. API to get all notifications
- [x] 4. API to update an notification

Optional:
1. JWT Authentication
2. WebSocket Auth
3. Test suit
